spring:
  datasource:
    url: jdbc:mysql://localhost:3306/batchdemo
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

      
  batch:
    initialize-schema: embedded
